version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - proxy-net
    secrets:
      - cert.pem
      - key.pem
      # Uncomment this if You want to provide Your own Diffie-Hellman parameters.
      # - dhparam.pem

secrets:
  cert.pem:
    file: ${CERT_PATH:-./nginx/cert.pem}
  key.pem:
    file: ${KEY_PATH:-./nginx/key.pem}
  # Uncomment this if You want to provide Your own Diffie-Hellman parameters.
  # dhparam.pem:
  # file: ${DHPARAM_PATH:-./nginx/dhparam.pem}

networks:
  proxy-net:
    name: pmd-reverse-proxy-net
    driver: bridge
