version: '3.7'
services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - proxy-net
    secrets:
      - cert.pem
      - key.pem
      # Generate this file with the command: "openssl dhparam -out dhparam.pem 4096"
      - dhparam.pem

secrets:
  cert.pem:
    file: ${CERT_PATH:-./nginx/cert.pem}
  key.pem:
    file: ${KEY_PATH:-./nginx/key.pem}
  dhparam.pem:
    file: ${DHPARAM_PATH:-./nginx/dhparam.pem}

networks:
  proxy-net:
    name: pmd-reverse-proxy-net
    driver: bridge
